baseurl = "https://developer.starinc.xyz/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Developer  Documents"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Powered by Star Inc."
  logo = "https://startw.cf/assets/images/logos/groups/star.jpg"
  favicon = "https://starinc.xyz/assets/images/icon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true

[Author]
  name = "Star Inc."
  github = "star-inc"


[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Star Inc. Global"
    url = "https://starinc.xyz/global/"
    weight = 3

[[menu.main]]
    identifier = "restapi"
    name = "RESTAPI"
    weight = 2

[[menu.main]]
    parent = "restapi"
    name = "Service"
    url = "restapi/service"
    weight = 1

[[menu.main]]
    parent = "restapi"
    name = "SDK"
    url = "restapi/sdk"
    weight = 2

[[menu.main]]
    parent = "restapi"
    name = "Code Sample"
    url = "restapi/sample"
    weight = 3