baseurl = "https://documents.starinc.xyz/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Public Documentation"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "Lanyon"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Powered by Star Inc."
  logo = "https://startw.cf/assets/images/logos/groups/star.jpg"
  favicon = "https://starinc.xyz/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true

[Author]
  name = "OSS Zone"
  url = "https://opensource.starinc.xyz"
  github = "star-inc"
  copyright = "Copyright(c) 2022 Star Inc.All Rights Reserved."
  copyright_url = "https://starinc.xyz"


[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Star Inc."
    url = "https://starinc.xyz/global/"
    weight = 5

[[menu.main]]
    identifier = "restapi"
    name = "RESTful API"
    weight = 3

[[menu.main]]
    parent = "restapi"
    name = "Basic API"
    url = "restapi/basic"
    weight = 1
